- name: Install additional packages
  hosts: localhost
  vars:
    packages:
      - vim
      - btrfs-progs
      - armbian-config
      - screen
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Installing Packages
   - name: Install Packages
     ansible.builtin.apt:
       pkg:
         "{{ packages }}"
       update_cache: yes
   - name: Remove useless packages from the cache
     ansible.builtin.apt:
       autoclean: yes
   - name: Remove dependencies that are no longer required
     ansible.builtin.apt:
       autoremove: yes
